apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    app: django-pod
spec:
  containers:
    - name: django-container
      image: docker.io/library/django_app:latest
      imagePullPolicy: Never
      env:
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-configmap
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: django-configmap
              key: DATABASE_URL
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "512Mi"
      ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: django-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort


