apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod  # Подписывается на pods с меткой "app: nginx"
  ports:
    - protocol: TCP
      port: 80
  type: NodePort