apiVersion: v1
kind: Service
metadata:
  name: nginx-unit-service
spec:
  selector:
    app: nginx-unit-pod  # Подписывается на pods с меткой "app: nginx-unit"
  ports:
    - protocol: TCP
      port: 8000  # Порт, на котором работает Nginx Unit
  type: NodePort