apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTBpZjQwbmY0bmY5M240
  ALLOWED_HOSTS: "*"
  DEBUG: "false"
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@192.168.100.2:5433/test_k8s
  # DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@d:5432/test_k8s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unit-config
data:
  unit.json: |
    {
        "listeners": {
            "*:80": {
                "pass": "routes/app"
            }
        },
        "routes": {
            "app": [
                {
                    "match": {
                        "uri": "/static/*"
                    },
                    "action": {
                        "share": "/"
                    }
                },
                {
                    "match": {
                        "uri": "/media/*"
                    },
                    "action": {
                        "share": "/"
                    }
                },
                {
                    "action": {
                        "pass": "applications/app"
                    }
                }
            ]
        },
        "applications":{
          "app": {
                "type":"python",
                "path":"/code/",
                "module":"project.wsgi",
                "environment": {
                    "DJANGO_SETTINGS_MODULE": "project.settings",
                }
            }
        }
    }
